name: ECC24_TR_Improved_QN_PO_for_MPC_in_RL
channels:
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.08.22=haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.1.2=py311haa95532_0
  - console_shortcut=0.1.1=4
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ipykernel=6.25.0=py311h746a85d_0
  - ipython=8.15.0=py311haa95532_0
  - jedi=0.18.1=py311haa95532_1
  - jupyter_client=8.1.0=py311haa95532_0
  - jupyter_core=5.3.0=py311haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - libsodium=1.0.18=h62dcd97_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - nest-asyncio=1.5.6=py311haa95532_0
  - openssl=3.0.11=h2bbff1b_2
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3=py311haa95532_0
  - platformdirs=3.10.0=py311haa95532_0
  - prompt-toolkit=3.0.36=py311haa95532_0
  - psutil=5.9.0=py311h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py311haa95532_1
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=305=py311h2bbff1b_0
  - pyzmq=25.1.0=py311hd77b12b_0
  - setuptools=68.0.0=py311haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.3.3=py311h2bbff1b_0
  - traitlets=5.7.1=py311haa95532_0
  - tzdata=2023c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py311haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - aiofiles==23.2.1
      - aiosqlite==0.19.0
      - asyncua==1.0.4
      - casadi==3.6.3
      - cffi==1.16.0
      - contourpy==1.1.1
      - cryptography==41.0.4
      - cycler==0.12.1
      - do-mpc==4.6.0
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - keras==2.14.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - matplotlib==3.8.0
      - ml-dtypes==0.2.0
      - numpy==1.26.1
      - oauthlib==3.2.2
      - onnx==1.14.1
      - packaging==23.2
      - pillow==10.1.0
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pycparser==2.21
      - pyopenssl==23.2.0
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - scipy==1.11.3
      - sortedcontainers==2.4.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-intel==2.14.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - typing-extensions==4.8.0
      - urllib3==2.0.7
      - wrapt==1.14.1

    # install locally with:
    # conda env create -f PATH/TO/.environment.yml
    
    # Activate environment with:
    # conda activate ECC24_TR_Improved_QN_PO_for_MPC_in_RL
    
    # Clone the following repository from GitHub and checkout the correct version
    # git clone https://github.com/DeanBrandner/RL_Tools_for_MPC.git PATH/TO/RL_Tools_for_MPC
    # cd PATH/TO/RL_Tools_for_MPC
    # git checkout tags/v0.0.1
    
    # Add the repository to conda
    # conda develop /PATH/TO/RL_Tools_for_MPC